name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Help us improve this library by suggesting a new feature or enhancement.

  - type: input
    id: summary
    attributes:
      label: What do you want to add?
      description: A short and clear summary of the feature you'd like.
      placeholder: Support adjustable time that can be frozen/unfrozen
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature needed?
      description: What problem does this solve or what use case does it support?
      placeholder: In some tests, I want to simulate time moving forward and then freeze it at a point...

  - type: textarea
    id: proposal
    attributes:
      label: How could this be implemented?
      description: Share your idea of how it might work or links to related libraries.
      placeholder: Maybe we can add a new `AdjustableFakeTime` interface...

  - type: textarea
    id: checklist
    attributes:
      label: Implementation Checklist
      description: Optional list of tasks required to implement this feature
      placeholder: |
        - [ ] Define new interface
        - [ ] Write implementation
        - [ ] Add unit tests
        - [ ] Update documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else that might help us understand the request.
      placeholder: Links, screenshots, diagrams, etc.
