name: CI

on:
  push:
    branches: [main, release/**]
  pull_request:
    branches: [main, release/**]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Spotless Lint (all modules)
        run: ./gradlew spotlessCheck --no-daemon

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Assemble (faketime only)
        run: ./gradlew :faketime:assemble --no-daemon

  test-faketime:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Test (faketime)
        run: ./gradlew :faketime:test --no-daemon

  test-sample:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Test (sample)
        run: ./gradlew :sample:test --no-daemon
